In [3]:
import os
import sys
import urllib, io
import pickle

import numpy as np
import scipy.stats as stats
import pandas as pd
from sklearn.metrics import euclidean_distances, jaccard_score, pairwise_distances

import pymongo as pm
from collections import Counter
import json
import re
import ast

from PIL import Image, ImageOps, ImageDraw, ImageFont 
from IPython.core.display import HTML 

from io import BytesIO
import base64
import requests

import  matplotlib
from matplotlib import pylab, mlab, pyplot
%matplotlib inline
from IPython.core.pylabtools import figsize, getfigs
plt = pyplot
import matplotlib as mpl
mpl.rcParams['pdf.fonttype'] = 42

import seaborn as sns
sns.set_context('talk')
sns.set_style('darkgrid')

from IPython.display import clear_output

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore", message="numpy.dtype size changed")
warnings.filterwarnings("ignore", message="numpy.ufunc size changed")

sys.path.append("../../../stimuli/block_utils/")
import blockworld_utils as utils

In [6]:
experiment_name = 'build_components'

## directory & file hierarchy
proj_dir = os.path.abspath('../../..')
datavol_dir = os.path.join(proj_dir,'data')
analysis_dir = os.path.abspath(os.path.join(os.getcwd(),'..'))
results_dir = os.path.join(proj_dir,'results')

# paths specific to this experiment
experiment_results_dir = os.path.join(results_dir, experiment_name)
plot_dir = os.path.join(experiment_results_dir,'plots')
csv_dir = os.path.join(experiment_results_dir,'csv')
json_dir = os.path.join(experiment_results_dir,'json')

png_dir = os.path.abspath(os.path.join(datavol_dir,'png'))
jefan_dir = os.path.join(analysis_dir,'jefan')
will_dir = os.path.join(analysis_dir,'will')

## add helpers to python path
if os.path.join(proj_dir,'stimuli') not in sys.path:
    sys.path.append(os.path.join(proj_dir,'stimuli'))
    
if not os.path.exists(results_dir):
    os.makedirs(results_dir)
    
if not os.path.exists(plot_dir):
    os.makedirs(plot_dir)   
    
if not os.path.exists(csv_dir):
    os.makedirs(csv_dir)

In [7]:
# set vars 
import configparser
config = configparser.ConfigParser()
# this conf file contains mongoDB username and password
config_path = os.path.join(proj_dir, '..', 'defaults.conf')
config.read(config_path)

HOST = 'cogtoolslab.org' ## experiment server ip address
user = config['DB']['username']
pw = config['DB']['password']
host = 'cogtoolslab.org' ## cocolab ip address

# have to fix this to be able to analyze from local
import pymongo as pm
conn = pm.MongoClient(f'mongodb://{user}:{pw}@127.0.0.1')
db = conn['block_construction']
coll = db['build_components']

In [8]:
# plugin names ({'datatype': 'trial_end'} & {'trial_type': xxxxxxxx})

# encode
BUILD_COPY = 'block-tower-building-undo'
TOWER_VIEWING = 'block-tower-viewing'
MATCH = 'block-tower-match-to-sample'
BUILD_WM = 'block-tower-building-undo-nostim'

ENCODE_TASKS = [BUILD_COPY, TOWER_VIEWING, MATCH, BUILD_WM]

# decode 
OLD_NEW = 'block-tower-old-new-img'
BUILD_RECALL = 'block-tower-building-recall-choose-color'

DECODE_TASKS = [OLD_NEW, BUILD_RECALL]

# additional data types ({'datatype': xxxxxx})
BLOCK = 'block_placement' # check that this is saved from all building plugins (BUILD_COPY, BUILD_WM, BUILD_RECALL)
RESET = 'reset' # check that this is saved from all building plugins (BUILD_COPY, BUILD_WM, BUILD_RECALL)
UNDO = 'block_undo_placement' # check that this is saved from all building plugins (BUILD_COPY, BUILD_WM, BUILD_RECALL)
REDO = 'block_redo_placement' # check that this is saved from all building plugins (BUILD_COPY, BUILD_WM, BUILD_RECALL)

In [11]:
# iteration names

# iteration_name = 'build_components_cogsci_ve_old_new_data_run_through_2'
# iteration_name = 'build_components_cogsci_ve_recall_data_run_through'
# iteration_name = 'build_components_cogsci_wm_old_new_data_run_through'
# iteration_name = 'build_components_cogsci_wm_recall_data_run_through'


iteration_name = "build_components_cogsci_ve_old_new_prolific_pilot_0"
# iteration_name = "build_components_cogsci_ve_recall_prolific_pilot_0"
# iteration_name = "build_components_cogsci_wm_old_new_prolific_pilot_0"
# iteration_name = "build_components_cogsci_wm_recall_prolific_pilot_0"


iteration_names = [iteration_name]

# dataframe plan

df_encode: encode phase from all iterations

df_encode_ve: all visual exposure trials
df_encode_wm: all working memory trials

df_recall: recall only 
df_recog: old-new only


We rarely compare between VE and WM.
It's more important for us to compare conditions within recog and within recall

In [12]:
# all data
query = coll.find({"$and":[
                        {'iterationName': { '$in': iteration_names }},
                        ]})
df_all = pd.DataFrame(query)
print(len(df_all))

5824

In [13]:
df_all.columns

Index(['_id', 'rt', 'url', 'trial_type', 'trial_index', 'time_elapsed',
       'internal_node_id', 'experimentName', 'iterationName', 'workerID',
       'gameID', 'studyLocation', 'datatype', 'view_history', 'success',
       'timeout', 'failed_images', 'failed_audio', 'failed_video',
       'n_blocks_when_reset', 'block_str', 'tower_id', 'tower_A_tall_id',
       'tower_A_wide_id', 'tower_B_tall_id', 'tower_B_wide_id',
       'tower_id_tall', 'composite_id', 'trial_num', 'absolute_time',
       'trial_start_time', 'relative_time', 'stimulus', 'condition', 'n_block',
       'n_resets', 'towerColor', 'timeAbsolute', 'timeRelative', 'blocks',
       'discreteWorld', 'eventType', 'block', 'endReason', 'trial_finish_time',
       'rep', 'response', 'novelty', 'response_meaning', 'response_correct',
       'key_presses', 'distractorKind'],
      dtype='str')

In [14]:
df_all.trial_type.unique()

<StringArray>
[            'external-html',              'instructions',
                   'preload', 'block-tower-building-undo',
       'block-tower-viewing',   'block-tower-old-new-img',
               'survey-text']
Length: 7, dtype: str

In [15]:
# I don't think metadata is saved anywhere.
query = coll.find({"$and":[
                        {'datatype':'metadata'},
                        {'iterationName': { '$in': iteration_names }},
                        ]})
df_meta = pd.DataFrame(query)
print(len(df_meta))

0

In [16]:
# exit survey responses
query = coll.find({"$and":[
                        {'iterationName': { '$in': iteration_names }},
                        {'trial_type': {'$in': ['survey-text']}}
                        ]})
df_survey = pd.DataFrame(query)
print(len(df_survey))
_ = [print(response) for response in df_survey.response]

50
{'technical': 'No', 'confused': 'No', 'comments': 'Thank you'}
{'technical': 'no', 'confused': 'no', 'comments': ''}
{'technical': 'No', 'confused': 'No', 'comments': 'Very difficult!'}
{'technical': 'no', 'confused': 'at the start but made more sense was i placed the blocks', 'comments': 'no'}
{'technical': 'no', 'confused': 'no', 'comments': 'i found remembering the colors more difficult than remembering the shapes'}
{'technical': '', 'confused': '', 'comments': ''}
{'technical': 'No', 'confused': 'The instructions were very clear', 'comments': ''}
{'technical': 'no', 'confused': 'no', 'comments': ''}
{'technical': 'no', 'confused': 'nothing was confusing', 'comments': 'I had a great time and it was a lot of fun!'}
{'technical': 'No.', 'confused': "The only thing was making the first copy; I didn't realise the blocks would only stack in a certain way, but I got it eventually.", 'comments': 'This was hard! :)'}
{'technical': 'no', 'confused': 'no', 'comments': 'no'}
{'technical': 'None. Experiment works fine in Firefox.', 'confused': 'No.', 'comments': 'Very hard to recall shapes through study alone.'}
{'technical': 'no', 'confused': 'no', 'comments': 'no'}
{'technical': 'No', 'confused': 'No', 'comments': 'Really enjoyed participating :)'}
{'technical': 'Yes, some towers could only be constructed a specific way; I had to reset #12 in order to finish because it would not let me place blocks that would fit and be accurate.', 'confused': 'No.', 'comments': 'Thank you'}
{'technical': 'no', 'confused': 'no', 'comments': 'no'}
{'technical': 'Ran smoothly', 'confused': 'No', 'comments': 'Great Study!'}
{'technical': 'no', 'confused': 'no', 'comments': 'I actually enjoyed this.'}
{'technical': 'No', 'confused': 'No', 'comments': 'An interesting and fun study!'}
{'technical': 'no', 'confused': 'no', 'comments': ''}
{'technical': 'no', 'confused': 'no', 'comments': 'no'}
{'technical': 'no', 'confused': "At the start I couldn't get to put each brick where I wanted but later noticed that they all were set on a sequence.", 'comments': 'Interesting and engaging'}
{'technical': 'No', 'confused': 'No', 'comments': 'No'}
{'technical': 'no', 'confused': 'no', 'comments': 'i loved it'}
{'technical': 'No', 'confused': 'No', 'comments': 'No'}
{'technical': '', 'confused': '', 'comments': ''}
{'technical': '', 'confused': '', 'comments': ''}
{'technical': 'No', 'confused': 'No', 'comments': 'No'}
{'technical': 'No', 'confused': 'No', 'comments': 'No'}
{'technical': 'nO', 'confused': 'No, it was sraightforward', 'comments': 'Thanks for the opportunity'}
{'technical': 'No', 'confused': 'No', 'comments': 'No'}
{'technical': 'None', 'confused': 'None, everything was fine', 'comments': 'None'}
{'technical': 'no', 'confused': 'no ', 'comments': 'it was hard remembering the correct ones since i forgot them when i was copying'}
{'technical': 'no problems', 'confused': 'no problems', 'comments': 'no comments'}
{'technical': 'No', 'confused': 'No', 'comments': 'Thank you, Was Fun!'}
{'technical': 'No', 'confused': 'No', 'comments': 'It was fun and challenging!'}
{'technical': 'No, it was fine.', 'confused': 'Nope, it all made sense.', 'comments': 'I liked doing this and it was fun. Would love to do simmilar studies in the future.'}
{'technical': 'No', 'confused': 'No', 'comments': 'interesting and different type of study, thank you, hope my input is useful.'}
{'technical': 'No, it worked fine.', 'confused': "At first i found it confusing as shapes wouldn't go into certain places but then I knew i had put them in the wrong place and quickly understood how to make the shapes the right way", 'comments': ''}
{'technical': 'n/a', 'confused': 'hard to remember colors', 'comments': 'n/a'}
{'technical': '', 'confused': '', 'comments': ''}
{'technical': 'None', 'confused': 'None', 'comments': 'None'}
{'technical': 'no technical difficulties :)', 'confused': 'I thought the explanation was good', 'comments': 'Interesting study and fun at the same time'}
{'technical': 'No', 'confused': 'No', 'comments': 'It took me a little while to work out how to copy the towers. Eventually I worked out it was like tetrus.'}
{'technical': 'no', 'confused': 'no was all clear', 'comments': 'none'}
{'technical': '', 'confused': '', 'comments': ''}
{'technical': 'No', 'confused': 'strugling with mastering the procudures', 'comments': 'No'}
{'technical': 'No technical difficulties', 'confused': 'I was not confused at all', 'comments': 'I really enjoyed this experiment'}
{'technical': 'difficult trying to build the towers', 'confused': 'it was confusing trying to build the towers', 'comments': 'better explanation on how to build the towers needed'}
{'technical': 'No', 'confused': 'No', 'comments': 'None thanks'}

# trial end data

In [18]:
# trial-end
query = coll.find({"$and":[
                        {'iterationName': { '$in': iteration_names }},
                        {'datatype':'trial_end'},
                        {'trial_type': {'$nin': ['instructions','preload','external-html','survey-text']}}
                        ]})
df_trial = pd.DataFrame(query)
print(len(df_trial))

1213

In [19]:
df_trial.relative_time

0        76748
1        15031
2        35913
3        40226
4       105872
         ...
1208      2475
1209      3351
1210      4015
1211      2905
1212    396921
Name: relative_time, Length: 1213, dtype: int64

In [20]:
df_trial

,_id,timeAbsolute,timeRelative,blocks,discreteWorld,eventType,endReason,block_str,tower_id,tower_A_tall_id,...,gameID,studyLocation,datatype,response,rt,novelty,response_meaning,response_correct,key_presses,distractorKind
0,659cb0f2c5c2296bd578d089,1.704768e+12,177466.0,"[{'x': 5, 'y': 0, 'width': 1, 'height': 2}, {'...","[[True, True, True, True, True, True, True, Tr...",trial_end,perfect-reconstruction-translation,0000000000000000011100000110000011100000111100...,talls_101_127,tall_101,...,9458-19ad828d-8101-4a85-bb7d-682c2d3be804,Prolific,trial_end,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,659cb0f8c5c2296bd578d08b,NaN,NaN,NaN,NaN,NaN,NaN,0000000000000000101000001010000011110000111100...,talls_116_115,tall_116,...,5426-41684701-dee6-4b7a-b086-9ee03b9d3adb,Prolific,trial_end,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,659cb11bc5c2296bd578d0ac,1.704768e+12,218004.0,"[{'x': 7, 'y': 0, 'width': 2, 'height': 1}, {'...","[[True, True, True, True, True, True, True, Tr...",trial_end,perfect-reconstruction-translation,0000000000000000111000001010000010110000111000...,talls_126_114,tall_126,...,9458-19ad828d-8101-4a85-bb7d-682c2d3be804,Prolific,trial_end,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,659cb125c5c2296bd578d0b2,1.704768e+12,174546.0,"[{'x': 5, 'y': 0, 'width': 2, 'height': 1}, {'...","[[True, True, True, True, True, True, True, Tr...",trial_end,perfect-reconstruction-translation,0000000000000000011100000110000011100000111100...,talls_101_127,tall_101,...,5426-41684701-dee6-4b7a-b086-9ee03b9d3adb,Prolific,trial_end,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,659cb126c5c2296bd578d0b4,1.704768e+12,173755.0,"[{'x': 5, 'y': 0, 'width': 1, 'height': 2}, {'...","[[True, True, True, True, True, True, True, Tr...",trial_end,perfect-reconstruction-translation,0000000000000000011100000110000011100000111100...,talls_101_127,tall_101,...,2225-44e783ae-b85d-4333-b0f5-b41e38786391,Prolific,trial_end,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1208,659f32ffc5c2296bd57949ac,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3263-95310aa2-2340-4e8f-9bd8-b9035b8a9d1e,Prolific,trial_end,m,2027.4,new,new,1.0,1.0,vertical_flip
1209,659f3305c5c2296bd57949b2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3263-95310aa2-2340-4e8f-9bd8-b9035b8a9d1e,Prolific,trial_end,m,2904.5,new,new,1.0,1.0,tall_swap
1210,659f330bc5c2296bd57949b8,NaN,NaN,NaN,NaN,NaN,NaN,0000000000000000010100000101000011110000110100...,talls_101_097,tall_101,...,3263-95310aa2-2340-4e8f-9bd8-b9035b8a9d1e,Prolific,trial_end,m,3584.6,old,new,0.0,1.0,NaN
1211,659f3311c5c2296bd57949bb,NaN,NaN,NaN,NaN,NaN,NaN,0000000000000000011000000110000011110000011100...,talls_097_115,tall_097,...,3263-95310aa2-2340-4e8f-9bd8-b9035b8a9d1e,Prolific,trial_end,z,2478.3,old,old,1.0,1.0,NaN
1212,659f33c4c5c2296bd5794a2d,NaN,NaN,NaN,NaN,NaN,NaN,0000000000000000111100001010000010100000101100...,talls_125_127,tall_125,...,4098-49d1ad53-b450-4859-b1ba-9fc9ca6f7ff3,Prolific,trial_end,m,396759.0,old,old,1.0,1.0,NaN

## encode phase

In [21]:
# learning/ exposure trials

query = coll.find({"$and":[
                        {'iterationName': { '$in': iteration_names }},
                        {'datatype': 'trial_end'},
                        {'trial_type':{ '$in': ENCODE_TASKS }},
                        ]})
df_encode = pd.DataFrame(query)
print(len(df_encode))
if len(df_encode) > 0:
    print('encode trials found:', list(df_encode.trial_type.unique()))

613
encode trials found: ['block-tower-building-undo', 'block-tower-viewing']

In [22]:
# in the WM versions, 'block-tower-viewing' trials appear in both conditions as the 'STUDY' part of both tasks

## decode phase

In [23]:
# old-new judgements
query = coll.find({"$and":[
                        {'iterationName': { '$in': iteration_names }},
                        {'datatype': 'trial_end'},
                        {'trial_type':{ '$in': DECODE_TASKS }},
                        ]})
df_decode = pd.DataFrame(query)
print(len(df_decode))
if len(df_decode) > 0:
    print('decode trials found:', list(df_decode.trial_type.unique()))

600
decode trials found: ['block-tower-old-new-img']

In [24]:
# recalled towers are saved one per trial, in up to 6 trials
query = coll.find({"$and":[
                        {'iterationName': { '$in': iteration_names }},
                        {'datatype': 'trial_end'},
                        {'trial_type': BUILD_RECALL},
                        ]})
df_recalled_towers = pd.DataFrame(query)
print(len(df_recalled_towers))

0

## additional data

In [25]:
# block placements
query = coll.find({"$and":[
                        {'datatype': BLOCK},
                        {'iterationName': { '$in': iteration_names }},
                        ]})
df_block = pd.DataFrame(query)
print(len(df_block))
print('individual block data found in:', list(df_block.trial_type.unique()))

3333
individual block data found in: ['block-tower-building-undo']

In [26]:
# resets
query = coll.find({"$and":[
                        {'datatype': RESET},
                        {'iterationName': { '$in': iteration_names }},
                        ]})
df_reset = pd.DataFrame(query)
print(len(df_reset))
if len(df_reset) > 0:
    print('reset data found in:', list(df_reset.trial_type.unique()))

400
reset data found in: ['block-tower-building-undo']

In [27]:
# undos
query = coll.find({"$and":[
                        {'datatype': UNDO},
                        {'iterationName': { '$in': iteration_names }},
                        ]})
df_undo = pd.DataFrame(query)
print(len(df_undo))
if len(df_undo) > 0:
    print('undo data found in:', list(df_undo.trial_type.unique()))

495
undo data found in: ['block-tower-building-undo']

In [28]:
# redos
query = coll.find({"$and":[
                        {'datatype': REDO},
                        {'iterationName': { '$in': iteration_names }},
                        ]})
df_redo = pd.DataFrame(query)
print(len(df_redo))
if len(df_redo) > 0:
    print('redo data found in:', list(df_redo.trial_type.unique()))

7
redo data found in: ['block-tower-building-undo']

In [29]:
df_undo_redo = pd.concat([df_undo, df_redo], ignore_index=True)
df_construction_procedure = pd.concat([df_block, df_undo, df_redo, df_reset], ignore_index=True)\
                              .sort_values(['gameID','trial_num','relative_time'], ascending=True).reset_index()

In [30]:
df_encode.trial_type.unique()

<StringArray>
['block-tower-building-undo', 'block-tower-viewing']
Length: 2, dtype: str

In [31]:
df_decode.trial_type.unique()

<StringArray>
['block-tower-old-new-img']
Length: 1, dtype: str

In [32]:
df_block.trial_type.unique()

<StringArray>
['block-tower-building-undo']
Length: 1, dtype: str

In [33]:
df_reset.trial_type.unique()

<StringArray>
['block-tower-building-undo']
Length: 1, dtype: str

In [34]:
df_construction_procedure.datatype.unique()

<StringArray>
['reset', 'block_placement', 'block_undo_placement', 'block_redo_placement']
Length: 4, dtype: str

In [35]:
df_construction_procedure.trial_type.unique()

<StringArray>
['block-tower-building-undo']
Length: 1, dtype: str

In [36]:
df_construction_procedure[['gameID','trial_num','relative_time','datatype','trial_type']]

,gameID,trial_num,relative_time,datatype,trial_type
0,0134-b328424d-0192-456d-b503-0cecd6837e12,1,71,reset,block-tower-building-undo
1,0134-b328424d-0192-456d-b503-0cecd6837e12,1,6788,block_placement,block-tower-building-undo
2,0134-b328424d-0192-456d-b503-0cecd6837e12,1,10024,block_placement,block-tower-building-undo
3,0134-b328424d-0192-456d-b503-0cecd6837e12,1,13216,block_placement,block-tower-building-undo
4,0134-b328424d-0192-456d-b503-0cecd6837e12,1,16882,block_placement,block-tower-building-undo
...,...,...,...,...,...
4230,9887-d3e2b07d-fac6-4dc8-9531-1ef0bd93322d,3,14172,block_placement,block-tower-building-undo
4231,9887-d3e2b07d-fac6-4dc8-9531-1ef0bd93322d,3,17140,block_placement,block-tower-building-undo
4232,9887-d3e2b07d-fac6-4dc8-9531-1ef0bd93322d,3,18907,block_placement,block-tower-building-undo
4233,9887-d3e2b07d-fac6-4dc8-9531-1ef0bd93322d,3,32230,block_placement,block-tower-building-undo
4234,9887-d3e2b07d-fac6-4dc8-9531-1ef0bd93322d,3,33815,block_undo_placement,block-tower-building-undo

## export data

In [37]:
print(experiment_results_dir)

/Users/sean/Documents/code/zipping/results/build_components

In [38]:
df_encode.to_csv(experiment_results_dir + '/cogsci24/df_encode_{}.csv'.format(iteration_name))
df_decode.to_csv(experiment_results_dir + '/cogsci24/df_decode_{}.csv'.format(iteration_name))
df_block.to_csv(experiment_results_dir + '/cogsci24/df_block_{}.csv'.format(iteration_name))
df_reset.to_csv(experiment_results_dir + '/cogsci24/df_reset_{}.csv'.format(iteration_name))
df_construction_procedure.to_csv(experiment_results_dir + '/cogsci24/df_construction_procedure_{}.csv'.format(iteration_name))
if len(df_recalled_towers) > 0:
    df_recalled_towers.to_csv(experiment_results_dir + '/cogsci24/df_recalled_towers_{}.csv'.format(iteration_name))

In [39]:
! open ~/zipping/results/build_components/cogsci24/

The file /Users/sean/zipping/results/build_components/cogsci24 does not exist.

### Exclusion criteria (implement in analysis scripts)

In [1212]:
# df_all_trial = pd.concat([df_learn, df_recalled_towers], ignore_index=True)

In [1213]:
# # remove experimenter data
# remove_tests = False

# if remove_tests:
#     df_build = df_build[~df_build.workerID.isna()]
#     df_survey = df_survey[~df_survey.workerID.isna()]
#     df_learn = df_learn[~df_learn.workerID.isna()]
#     df_recall = df_recall[~df_recall.workerID.isna()]

In [1214]:
# df_learn.groupby(['workerID','gameID']).apply(len)

In [1215]:
# # remove incomplete datasets (build recall)
# remove_incomplete_datasets = True
# n_expected_learn_trials = 18

# if remove_incomplete_datasets:
#     a = df_learn.groupby('gameID').apply(len) == n_expected_learn_trials
#     complete_zipping_set_gameIDs = list(a[a].index)
#     df_trials = df_all_trial[df_all_trial.gameID.isin(complete_zipping_set_gameIDs)]
#     df_learn = df_learn[df_learn.gameID.isin(complete_zipping_set_gameIDs)]
#     df_recalled_towers = df_recalled_towers[df_recalled_towers.gameID.isin(complete_zipping_set_gameIDs)]
    
#     incomplete_zipping_set_gameIDs = list(a[~a].index)
#     print(str(len(incomplete_zipping_set_gameIDs)) + ' ppts removed for incomplete data')
#     print(str(len(complete_zipping_set_gameIDs)) + ' ppts left')
# else: 
#     print('No ppts removed')